version: '3.3'
services:
  appserver:
    container_name: wildfly-unipol
    build:
      context: delivery
      dockerfile: delivery/Dockerfile
    image: jboss/wildfly:14.0.0.Final
    ports:
      - 9990:9990
      - 8787:8787
      - 8081:8080
    volumes:
      - ./delivery/deployments/:/opt/jboss/wildfly/standalone/deployments/

